### ISSUE TITLE
F4RegPath won´t launch

### ISSUE THREAD

**Issue by ranXeron** [BibleClinger/F4RegPath#2]
My System:
Windows 10 Pro for Workstations  / 22H2
AMD Ryzen 5 3600 6-Core Processor 3.60 GHz
16,0 GB Ram
Nvidia RTX 3900

Falcon BMS was previously installed and removed with BMS uninstaller.

Upon executing **F4RegPath.exe** as Admin I get the following errors and the program quits.

![Screenshot 2023-02-02 092552](https://user-images.githubusercontent.com/9581642/216272666-4b1a7926-539e-4f46-8a1a-d0cf8eb4b241.jpg)

![Screenshot 2023-02-02 092614](https://user-images.githubusercontent.com/9581642/216272755-8cec5f4e-ed01-4bda-bd3b-9929e2e7d40d.jpg)

**Comment by BibleClinger** [comment]
I think I see what is going on. If you don't have the Benchmark Sims registry entry, then the program will do this. I thought I had taken this into account, but oh well. The good news is that if this is the case, then you don't need this program in order to reinstall Falcon BMS. 🙂

**Comment by BibleClinger** [comment]
I added a new release with the intended behavior.

**Comment by ranXeron** [comment]
Just checked the new release - still the registry error windows pops up

![Screenshot 2023-02-02 123328](https://user-images.githubusercontent.com/9581642/216314696-0096f7ba-9ed9-4f62-8914-bb9d79426ae0.jpg)


but then the program runs as intended.

![Screenshot 2023-02-02 123509](https://user-images.githubusercontent.com/9581642/216314767-d598efce-711b-45f2-85c2-997a040086dd.jpg)

In my opinion the text in the error window is a bit misleading -  maybe "No traces of a falcon BMS installation were found  -  Perhaps this is a permission issue. Perhaps BMS was never installed or it was completely uninstalled before." would be better.

Also the version number still shows 0.0.2 alpha....

**Comment by BibleClinger** [comment]
Thanks for the feedback. I'll adjust the version number, and clarify the error message. I think that ought to address the issue.
